[project]
name = "telbot-vnpt"
version = "0.1.0"
description = "A Telegram bot using VNPT AI services"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.12.3",
    "pytelegrambotapi>=4.29.1",
]
